### ISSUE TITLE
Error with v3.4.2

### ISSUE THREAD

**Issue by ujwal-setlur** [tgreyuk/typedoc-plugin-markdown#184] opened 2021-01-22 02:14 UTC
I am getting this error with 3.4.2. 3.4.0 works fine:

```bash
> typedoc --theme markdown --out apidocs src

Info: Loaded plugin node_modules/typedoc-plugin-markdown
Rendering [================================--------] 78%TypeDoc exiting with unexpected error:
TypeError: Cannot read property 'map' of undefined
    at propertyTable (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/typedoc-plugin-markdown/dist/resources/helpers/property-table.js:9:30)
    at /Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/typedoc-plugin-markdown/dist/resources/helpers/parameter-table.js:28:56
    at Array.forEach (<anonymous>)
    at list (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/typedoc-plugin-markdown/dist/resources/helpers/parameter-table.js:21:16)
    at Array.parameterTable (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/typedoc-plugin-markdown/dist/resources/helpers/parameter-table.js:14:16)
    at Array.wrapper (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:145)
    at prog (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at SignatureReflection.<anonymous> (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/handlebars/dist/cjs/handlebars/helpers/with.js:32:14)
    at SignatureReflection.wrapper (/Users/ujwal/Work/byte/software/repos/micro/micro-discount/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
```

Here are the relevant packages and versions:
```ts
    "typedoc": "0.20.16",
    "typedoc-plugin-markdown": "3.4.2",
    "typescript": "4.1.3"
```

**Comment by B4nan** [comment] 2021-01-22 09:19
Same here, this time with docusaurus. Failed CI build with more details:

https://github.com/mikro-orm/mikro-orm/runs/1747663985

**Comment by tgreyuk** [comment] 2021-01-22 09:41
sorry will look into why none of the tests picked that up. should be fixed in 3.4.3.

**Comment by B4nan** [comment] 2021-01-22 14:00
I can confirm it helped: 

https://github.com/mikro-orm/mikro-orm/runs/1747934897

Btw there is one more issue I had after upgrading the whole typedoc/docusaurus/typedoc-plugin-markdown thing - previously sidebar file was generated before docusaurus tried to load it - so it was ok to do simple `require()` from the main sidebar file. That seems to be no longer true, without the file being present, the build fails. I did work this around by first checking if the file is there, and calling `build` first before doing `deploy` (which again builds the whole thing - this time with the typedoc sidebar being available. While that works, it increases the build time a lot (the whole docs build takes around 30min now, before it was around half of that).

**Closed** 2021-01-22 14:00 UTC

**Comment by tgreyuk** [comment] 2021-01-22 14:10
@B4nan thanks for this. have opened another ticket for this one - https://github.com/tgreyuk/typedoc-plugin-markdown/issues/185. I think this must be a regression due to fixing an issue with multiple instances. Let me know if you notice anything else.
