### ISSUE TITLE
How to document types? (Unions and Intersection Types)

### ISSUE THREAD

**Issue by mrousavy** [tgreyuk/typedoc-plugin-markdown#207] opened 2021-03-18 09:38 UTC
## Search Terms

type, export type, types, interface, interfaces, union type, intersection type, unions

### Can't document union types

It is not possible to document the individual values of union types, so I have to adjust the description to manually list them:

```ts
/**
 * Represents the camera device position.
 *
 * * `"back"`: Indicates that the device is physically located on the back of the system hardware
 * * `"front"`: Indicates that the device is physically located on the front of the system hardware
 *
 * #### iOS only
 * * `"unspecified"`: Indicates that the device's position relative to the system hardware is unspecified
 *
 * #### Android only
 * * `"external"`: The camera device is an external camera, and has no fixed facing relative to the device's screen. (Android only)
 */
export type CameraPosition = 'front' | 'back' | 'unspecified' | 'external';
```

Is there a better solution for this so I can correctly document each union (`front`, `back`, ...) with TypeDoc checking if I missed anything and even allowing me to link to it?

### No "types" category in output

Documenting an interface is easy;

```ts
/**
 * document Point here
 */
export interface Point {
  /**
   * document x here
   */ 
  x: number;
  /**
   * document x here
   */ 
  y: number;
}
```

...and TypeDoc places it under the "Interfaces" section/"folder".

But if I make `Point` a `type` instead of an `interface`;

```ts
/**
 * document Point here
 */
export type Point = ReadOnly<{
  /**
   * document x here
   */ 
  x: number;
  /**
   * document x here
   */ 
  y: number;
}>;
```

...TypeDoc does not place `Point` under a "Types" section in the output but rather "ignores" it so you can only find it under "Modules". Also, by using `ReadOnly` the type is very verbose, but I suppose that's just how it works.

You can see this in action at [VisionCamera documentation](https://cuvent.github.io/react-native-vision-camera/docs/api/), where there is an "Interfaces" section on the left but no "Types" (or "Unions" or whatever) section. Instead, `CameraPosition` can only be found under "Modules" > "CameraPosition".

## Suggested Solution

Add a "Types" output category just like "Interfaces", and allow individual union types to be documented.

**Comment by tgreyuk** [comment] 2021-03-18 21:00
This is not something this plugin can control and in any case it is not currently achievable. There are noises that it may be possible in the future. These references should provide further background:

- https://github.com/TypeStrong/typedoc/issues/1148
- https://github.com/microsoft/tsdoc/issues/164

**Comment by mrousavy** [comment] 2021-03-19 08:34
Oh I see, thanks 👍

**Comment by tgreyuk** [comment] 2021-06-15 09:33
Closing as duplicate of https://github.com/TypeStrong/typedoc/issues/1540.

**Closed by tgreyuk** 2021-06-15 09:33 UTC
